pt_main/urls.py
"""
URLs for routing paralleltext application
"""

from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'paralleltext.views.home', name='home'),
    # url(r'^paralleltext/', include('paralleltext.foo.urls')),
    url(r'^$', 'home.views.index'),
    url(r'^login/', 'users.views.user_auth'),
    url(r'^logout/', 'users.views.user_logout'),
    url(r'^register/', 'users.views.user_reg'),
    url(r'^account/', 'users.views.user_acct'),
    url(r'^account_pass/', 'users.views.user_acct_pass'),
    url(r'^account_delete/', 'users.views.del_acct'),
    url(r'^help/', 'help.views.viewhelp'),
    #url(r'^ptext/', 'ptext.views.popup_demo'),
    url(r'^parallel_display/', 'parallel_display.views.select_book'),
    url(r'^upload/', 'content_mgmt.views.upload'),
    url(r'^upload_confirm/', 'content_mgmt.views.upload_confirm'),
    url(r'^upload_fail/', 'content_mgmt.views.upload_fail'),
    url(r'^search/', 'search.views.search'),
    url(r'^dictionary/', 'dictionary.views.viewdict'),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

users/models.py
"""
models.py defines the data and behavior that is being stored in the database.
The register models contains how the user account information should be stored.
"""
from django.db import models
from django.contrib.auth.models import User
from languages.models import Languages

class UserAccount(models.Model):
    """
    UserAccount stores the account settings for the user.
    This is an extension of the user_auth table in the database.
    """
    user = models.ForeignKey(User, unique=True)
    is_contentmgr = models.BooleanField(default=False)
    native_lang = models.ForeignKey(Languages)
    #learn_lang = models.ForeignKey(Languages)

users/forms.py
"""
forms.py creates and defines the structure for the forms before displaying them
on the webpage. The register forms determines the requirements and behavior of
the input fields presented to the user.
"""
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import UserAccount
from languages.models import Languages

class AccountCreateForm(UserCreationForm):
    """
    AccountCreateForm provides the form model that creates the user account
    based on provided credentials.
    Required: Username, Password, Password Confirmation, and Native Language.
    Optional: Email Address, First Name, Last Name.
    """
    #def __init__(self):
        #pass

    email = forms.EmailField(
        max_length = 75,
        required = False,
        label = 'Email Address',
    )

    first_name = forms.CharField(
        max_length = 30,
        required = False,
        label = 'First Name',
    )

    last_name = forms.CharField(
        max_length = 30,
        required = False,
        label = 'Last Name',
    )

    native_lang = forms.ModelMultipleChoiceField(
        widget = forms.Select,
        queryset = Languages.objects.all().values_list('name', flat=True),
        label = 'Native Language'
    )

    #learn_lang = forms.ModelChoiceField(
        #widget = forms.Select,
        #queryset = Languages.objects.all(),
        #label = 'Learning Language'
    #)

    class Meta:
        """
        Model metadata used to identify attributes in POST data when submitting
        a registration form. Required by users/views.py --> form =
        AccountCreateForm(request.Post). Throws error if removed.
        """
        def __init__(self):
            pass

        model = UserAccount
        fields = (
            'username',
            'password1',
            'password2',
            'email',
            'first_name',
            'last_name',
            'native_lang',
            #'learn_lang',
        )



class AccountManageForm(forms.ModelForm):
    """
    AccountManageForm provides the form model that retrieves and displays the
    user's information based on the data already stored in the database.
    """
    #def __init__(self):
        #pass

    email = forms.EmailField(
        max_length = 75,
        required = False,
        label = 'Email Address',
    )

    first_name = forms.CharField(
        max_length = 30,
        required = False,
        label = 'First Name',
    )

    last_name = forms.CharField(
        max_length = 30,
        required = False,
        label = 'Last Name',
    )

    native_lang = forms.ModelChoiceField(
        widget = forms.Select,
        queryset = Languages.objects.all(),
        label = 'Native Language'
    )

    #learn_lang = forms.ModelChoiceField(
        #widget = forms.Select,
        #queryset = Languages.objects.all(),
        #label = 'Learning Language'
    #)

    class Meta:
        """
        Model metadata used to identify attributes in POST data when submitting
        a registration form. Required by users/views.py --> form =
        AccountCreateForm(request.Post). Throws error if removed.
        """
        def __init__(self):
            pass

        model = UserAccount
        fields = (
            'email',
            'first_name',
            'last_name',
            'native_lang',
            #'learn_lang',
        )



class AccountManagePassForm(forms.ModelForm):
    """
    AccountManagePassForm provides the form model that allows the user to
    change their account password.
    """
    #def __init__(self):
        #pass

    pass_old = forms.CharField(
        widget=forms.PasswordInput,
        max_length = 30,
        required = True,
        label = 'Old Password',
    )

    pass_new1 = forms.CharField(
        widget = forms.PasswordInput,
        max_length = 30,
        required = True,
        label = 'New Password',
    )

    pass_new2 = forms.CharField(
        widget = forms.PasswordInput,
        max_length = 30,
        required = True,
        label = 'New Password (again)',
    )

    class Meta:
        """
        Model metadata used to identify attributes in POST data when submitting
        a registration form. Required by users/views.py --> form =
        AccountCreateForm(request.Post). Throws error if removed.
        """
        def __init__(self):
            pass

        model = UserAccount
        fields = (
            'pass_old',
            'pass_new1',
            'pass_new2',
        )

    def clean(self):
        """
        clean cleans the data before comparing them and inserting into the
        database. Sends exception errors if tests are not passed.
        """
        pass_new1 = self.cleaned_data.get('pass_new1')
        pass_new2 = self.cleaned_data.get('pass_new2')

        if pass_new1 and pass_new2 and pass_new1 != pass_new2:
            raise forms.ValidationError("Passwords do not match.")

        return self.cleaned_data

users/views.py
"""
views.py decides what to display on webpage based on current conditions.
"""

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from users.forms import AccountCreateForm, AccountManageForm
from users.forms import AccountManagePassForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from users.models import UserAccount
from languages.models import Languages

def user_reg(request):
    """
    The register views checks if the user has submitted information and displays
    the corresponding page after processing the information.
    """
    form = AccountCreateForm(request.POST)

    if request.method == 'POST':
        #if form.is_valid():
            new_user = User.objects.create_user(
                username=request.POST.get('username'),
                email=request.POST.get('email'),
                password=request.POST.get('password1'),
                first_name=request.POST.get('first_name'),
                last_name=request.POST.get('last_name'))
            lang = Languages.objects.get(name=request.POST.get('native_lang'))
            extra_info = UserAccount(user_id=new_user.pk, native_lang=lang)
            extra_info.save()
            return HttpResponseRedirect('/')
    else:
        form = AccountCreateForm()

    return render(request, 'users/register.html', {'form': form})



def user_auth(request):
    """
    This function authenticates a user on login, either approving or rejecting
    the provided credentials.
    """
    status = ""
    username = password = ''

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                #status = "You have successfully logged in!"
                return HttpResponseRedirect('/')
            else:
                status = "You have logged in but your account is inactive.\
                  Please contact an administrator."
        else:
            status = "Your username and/or password were incorrect."

    return render(request, 'users/login.html',
                  {'status': status})



def user_logout(request):
    """
    This function deauthenticates the current user from the system.
    """
    logout(request)
    response = redirect('home.views.index')
    response.delete_cookie('user_location')
    return response



def user_acct(request):
    """
    This function allows the current user to view their account information
    and perform any changes to them, if necessary.
    """
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        status = ""

        user = User.objects.get(username=request.user)
        lang_id = UserAccount.objects.get(user_id=request.user.pk).native_lang_id
        lang_name = Languages.objects.get(langID=lang_id)

        if request.method == 'POST':
            form = AccountManageForm(data=request.POST, instance=request.user)
            if form.is_valid():
                extra_info = UserAccount.objects.get(user_id=user.pk)
                extra_info.native_lang_id = request.POST.get('native_lang')
                extra_info.save()
                form.save()
                status = "Your account information has been saved."
            else:
                status = "Form is not valid."
        else:
            form = AccountManageForm(instance=request.user,
                                     initial={'native_lang': lang_name})

        return render(request, 'users/account.html',
                      {'form': form,
                       'status': status,
                       'username': user.username})



def user_acct_pass(request):
    """
    This function allows the current user to view their account information
    and perform any changes to them, if necessary.
    """
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        status = ""

        user = User.objects.get(username=request.user)

        form = AccountManagePassForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                user.set_password(request.POST.get('pass_new1'))
                user.save()
                status = "Your account information has been saved."
            else:
                status = "Form is not valid."
        else:
            form = AccountManagePassForm()

        return render(request, 'users/account_pass.html',
                      {'form': form,
                       'status': status,
                       'username': user.username})



def del_acct(request):
    """
    This function allows the current user to delete their account from the
    system.
    """
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    else:
        user = User.objects.get(username=request.user)
        user.delete()
        return HttpResponseRedirect('/')

users/templates/users/account.html
{% extends 'base.html' %}

{% block bodycontent %}
<h2>Account Management: {{ username }}</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.non_field_errors }}
            {{ status }}
            <tr height="50px">
                <td>Username</td>
                <td colspan=2>{{ username }}</td>
            </tr>
            <tr>
                <td><label for="id_email">{{ form.email.label }}</label></td>
                <td>{{ form.email }}</td>
                <td>{{ form.email.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_first_name">{{ form.first_name.label }}</label></td>
                <td>{{ form.first_name }}</td>
                <td>{{ form.first_name.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_last_name">{{ form.last_name.label }} </label></td>
                <td>{{ form.last_name }}</td>
                <td>{{ form.last_name.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_native_lang">{{ form.native_lang.label }} </label></td>
                <td>{{ form.native_lang }}</td>
                <td>{{ form.native_lang.errors }}</td>
            </tr>
            <tr>
                <td colspan=3><input type="submit" value="Update"></td>
            </tr>
        </table>
    </form>

    <a href="/account_pass/">Change Password</a><br>
    <a href="/account_delete/">Delete Account</a>
{% endblock %}

users/templates/users/account_pass.html
{% extends 'base.html' %}

{% block bodycontent %}
<h2>Account Management: {{ username }}</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.non_field_errors }}
            {{ status }}
            <tr>
                <td><label for="id_pass_old">{{ form.pass_old.label }}</label></td>
                <td>{{ form.pass_old }}</td>
                <td>{{ form.pass_old.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_pass_new1">{{ form.pass_new1.label }} </label></td>
                <td>{{ form.pass_new1 }}</td>
                <td>{{ form.pass_new1.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_pass_new2">{{ form.pass_new2.label }} </label></td>
                <td>{{ form.pass_new2 }}</td>
                <td>{{ form.pass_new2.errors }}</td>
            </tr>
            <tr>
                <td colspan=3><input type="submit" value="Update"></td>
            </tr>
        </table>
    </form>

    <a href="/account/">Change Account Information</a><br>
    <a href="/account_delete/">Delete Account</a>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block bodycontent %}
    <h2>Login</h2>
    {{ status }}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="username">Username</label></td>
                <td><input type="text" name="username" value="{{ username }}" /></td>
            </tr>
            <tr>
                <td><label for="password">Password</label></td>
                <td><input type="password" name="password" value="" /></td>
            </tr>
            <tr>
                <td colspan=2><input type="submit" value="Login" /></td>
            </tr>
        <table>
    </form>
    <p>Don't have an account? <a href="/register/">Register</a> for one today!</p>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block bodycontent %}
    <h2>Account Registration</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.non_field_errors }}
            <tr>
                <td><label for="id_username">{{ form.username.label }}</label></td>
                <td>{{ form.username }}</td>
                <td>{{ form.username.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_password1">{{ form.password1.label }}</label></td>
                <td>{{ form.password1 }}</td>
                <td>{{ form.password1.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_password2">{{ form.password2.label }}</label></td>
                <td>{{ form.password2 }}</td>
                <td>{{ form.password2.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_email">{{ form.email.label }}</label></td>
                <td>{{ form.email }}</td>
                <td>{{ form.email.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_first_name">{{ form.first_name.label }}</label></td>
                <td>{{ form.first_name }}</td>
                <td>{{ form.first_name.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_last_name">{{ form.last_name.label }} </label></td>
                <td>{{ form.last_name }}</td>
                <td>{{ form.last_name.errors }}</td>
            </tr>
            <tr>
                <td><label for="id_last_name">{{ form.native_lang.label }} </label></td>
                <td>{{ form.native_lang }}</td>
                <td>{{ form.native_lang.errors }}</td>
            </tr>
            <tr>
                <td colspan=3><input type="submit" value="Register"></td>
            </tr>
        </table>
    </form>
    <p>Already have an account? <a href="/login/">Login</a> with your account.</p>
{% endblock %}